url=jdbc:sqlserver://${DB_HOST:swp391g1server.database.windows.net}:${DB_PORT:1433};databaseName=${DB_NAME:swp391g1};encrypt=false;trustServerCertificate=true
userID=swp391_g1_admin
password=Huy123456